[tool.poetry]
name = "yaramo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "yaramo"}]

[tool.poetry.dependencies]
python = "^3.10"
pyproj = "^3.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
